services:
  acme-otel-collector:
    volumes:
      - ../../../config/stage/dev/otel/otel-collector-config-tls.yaml:/etc/otel-collector-config.yaml:z
      - ${CA_ROOT_CERT:-}:/rootca.pem:z
  acme-jaeger:
    volumes:
      - ../../../config/stage/dev/tls/acme.test+1.pem:/cert.pem:z
      - ../../../config/stage/dev/tls/acme.test+1-key.pem:/key.pem:z
      - ${CA_ROOT_CERT:-}:/rootca.pem:z
#    command:
#      - "--query.http.tls.enabled"
#      - "--query.http.tls.key=/key.pem"
#      - "--query.http.tls.cert=/cert.pem"
#      - "--query.http.tls.min-version=1.2"
#      - "--query.http.tls.max-version=1.3"
#      - "--collector.grpc.tls.enabled"
#      - "--collector.grpc.tls.key=/key.pem"
#      - "--collector.grpc.tls.cert=/cert.pem"
#      - "--collector.grpc.tls.min-version=1.2"
#      - "--collector.grpc.tls.max-version=1.3"
      # Jaeger sends traces to itself. If we only allow TLS inbound, we need to do this via the hostname
      # and validate the certificate
#      - "--reporter.grpc.tls.enabled"
#      - "--reporter.grpc.tls.ca=/rootca.pem"
#      - "--reporter.grpc.host-port=ops.acme.test:14250"
  acme-keycloak:
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: 'https://ops.acme.test:14317'
