services:
  acme-prometheus:
    image: prom/prometheus:v2.53.4
    user: "65534:1000"
    ports:
    - "9090:9090"
    volumes:
      - ../../../config/stage/dev/prometheus:/etc/prometheus:z
#      - ./run/prometheus:/prometheus:z
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
